### ISSUE TITLE
Avoid passing complicated objects by value if you can

### ISSUE THREAD

**Issue by kpu** [browsermt/mts#13]
This should have been passed by reference.  
https://github.com/browsermt/mts/blob/41978b4c225138432883a8c1abc98e7a86a31c2c/src/bergamot/request.cpp#L11

Also, it's not even clear what this is used for.

**Comment by jerinphilip** [comment]
https://github.com/browsermt/mts/blob/b30809f0af85760a701cde7f2d5910b0b6b74abd/src/bergamot/request.h#L50

https://github.com/browsermt/mts/blob/b30809f0af85760a701cde7f2d5910b0b6b74abd/src/bergamot/request.cpp#L13-L20

I understand the need to add variable names, will be done in a separate commit.
