### ISSUE TITLE
gettimeofday isn't monotonic

### ISSUE THREAD

**Issue by kpu** [browsermt/mts#14]
https://github.com/browsermt/mts/blob/41978b4c225138432883a8c1abc98e7a86a31c2c/src/bergamot/request.cpp#L23

```
NOTES
       The time returned by gettimeofday() is affected by discontinuous jumps in the system time (e.g., if the system
       administrator manually changes the system time).  If you need a monotonically increasing clock, see clock_get‐
       time(2).
```
Also do you even need a notion of clock time or is a sequence number sufficient to compare ages?

**Comment by jerinphilip** [comment]
Sequence number should be enough. Should we account for the case of overflow?

**Comment by kpu** [comment]
64 bits should be enough for everyone!
