### ISSUE TITLE
Race condition in barrier

### ISSUE THREAD

**Issue by kpu** [browsermt/mts#15]
Think about this code more:

https://github.com/browsermt/mts/blob/41978b4c225138432883a8c1abc98e7a86a31c2c/src/bergamot/request.cpp#L38-L40

Two threads could decrease the counter atomically then advance to see the counter is zero.  Both threads would execute the code.

**Comment by jerinphilip** [comment]
Using pre-increment operator which should be atomic. Closing.

https://github.com/browsermt/mts/blob/e79286cbc590847c03a285a4a001fb99d444c514/src/bergamot/request.cpp#L34-L44
