### ISSUE TITLE
Make private methods private

### ISSUE THREAD

**Issue by kpu** [browsermt/mts#19]
https://github.com/browsermt/mts/blob/b30809f0af85760a701cde7f2d5910b0b6b74abd/src/bergamot/batch_translator.h#L29-L50

It looks like `translate` and `mainloop` are not meant to be called from outside the class.  So they should be private.

**Comment by jerinphilip** [comment]
Internal functions are moved to private, closing.

https://github.com/browsermt/mts/blob/338d5f76bce2c970c9f2b3c240b13b35ef4f733c/src/bergamot/batch_translator.h#L23-L46
