### ISSUE TITLE
Why are there two identical functions that do the same thing

### ISSUE THREAD

**Issue by kpu** [browsermt/mts#8]
https://github.com/browsermt/mts/blob/41978b4c225138432883a8c1abc98e7a86a31c2c/src/bergamot/service.h#L19-L20

Just a confusing API.

**Comment by jerinphilip** [comment]
https://github.com/browsermt/mts/commit/c251551d8aef55f4f8008b0499eb3592f278edf6 takes care of this, for now. Wanted to use translate to switch between single-thread and multiple-thread implementations.

**Comment by jerinphilip** [comment]
Exists no longer, closing.
