### ISSUE TITLE
Way too big of a queue

### ISSUE THREAD

**Issue by kpu** [browsermt/mts#9]
The queue doesn't actually need to be that long:

https://github.com/browsermt/mts/blob/nuke/src/bergamot/service.cpp#L18

Keep in mind work is removed from the queue when a thread starts doing it.

**Comment by jerinphilip** [comment]
Set to `2*numWorkers` for now. 
https://github.com/browsermt/mts/blob/e79286cbc590847c03a285a4a001fb99d444c514/src/bergamot/service.cpp#L15
